### ISSUE TITLE
Paths with spaces in them cause errors

### ISSUE THREAD

**Issue by reversefold** [reversefold/magicreq#3]
```
/bin/sh: _venv/bin/pip: "/Users/jpatrin/src/magic: bad interpreter: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in main
  File "<stdin>", line 79, in bootstrap
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by reversefold** [comment]
Fixed in version 0.4.2
